# Generated by Django 5.2.1 on 2025-06-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='fecha_creacion',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='fecha_actualizacion',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='cursos', verbose_name='Imagen'),
        ),
    ]
