# Generated by Django 5.2.1 on 2025-08-02 00:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción de la actividad'),
        ),
    ]
