# Generated by Django 5.2.1 on 2025-08-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_actividad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
